title: Federal Enterprise Data Resources
email: datagov@gsa.gov
description: >-
  Federal Enterprise Data Resources are tools, best practices, and schema standards to facilitate the adoption of open data practices across the federal government
baseurl: "" # the subpath of your site, e.g. /blog
url: https://resources.data.gov
twitter_username: usdatagov
github_username:  gsa
dap_agency: GSA
searchgov_affiliate: datagov-resources

github:
  organization: GSA
  repository: resources.data.gov
  default_branch: master

styles:
  - assets/uswds/css/styles.css

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-sitemap
source: pages

defaults:
  - scope:
      path: ''
    values:
      layout: page

keep_files:
  - assets/js
  - assets/uswds

exclude:
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md
  - _js
  - _scss
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package-lock.json
  - package.json
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
